- name: Deploy FPL Assistant
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Connecting to GKE
      shell: gcloud container clusters get-credentials "{{ cluster_name }}" --zone "{{ zone }}" --project "{{ project_id }}"

    - name: Creating namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: fpl

    - name: Creating secret
      kubernetes.core.k8s:
        state: present
        namespace: fpl
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mysqldatabase
          type: Opaque
          stringData:
            DB_ROOT_PASS: "{{ root_pass }}"
            DB_USERNAME: "{{ db_user }}"
            DB_PASS: "{{ db_pass }}"

    - name: Creating storage class
      kubernetes.core.k8s:
        state: present
        namespace: fpl
        definition:
          apiVersion: v1
          kind: StorageClass
          metadata:
            name: fplstorage
          provisioner: kubernetes.io/gce-pd
          reclaimPolicy: Retain
          parameters:
            type: pd-standard
            fstype: ext4
            replication-type: none

    - name: Preparing annotations
      ansible.builtin.shell: date --utc '+%FT%TZ'
      register: date

    - name: Preparing deployment
      ansible.builtin.replace:
        path: ./full-deployment.yml
        regexp: 'annot-date'
        replace: "{{ date.stdout }}"

    - name: Checking deployment
      kubernetes.core.k8s:
        state: present
        namespace: fpl
        apply: yes
        src: full-deployment.yml

    - name: Cleanup config
      ansible.builtin.replace:
        path: ./full-deployment.yml
        regexp: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z'
        replace: 'annot-date'
