apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fpl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: 34.93.67.83.xip.io
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: frontend-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: api-service
              servicePort: 3001
---
