name: FPL Assistant Front-End CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm ci
    - name: Tests
      run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Container
      run: docker build -t strangeloop1710/fpl-react:latest .

    - name: Push Container
      run: docker push strangeloop1710/fpl-react:latest
