name: FPL Assistant Deployment

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ init-deploy ]

jobs:
  tag-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull frontend image
      run: docker pull strangeloop1710/fpl-react:pr-latest
    - name: Tag frontend image
      run: docker tag strangeloop1710/fpl-react:pr-latest strangeloop1710/fpl-react:latest
    - name: Push frontend image
      run: docker push strangeloop1710/fpl-react:latest
  tag-backend:
    needs: tag-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull backend image
      run: docker pull strangeloop1710/fpl-api:pr-latest
    - name: Tag backend image
      run: docker tag strangeloop1710/fpl-api:pr-latest strangeloop1710/fpl-api:latest
    - name: Push backend image
      run: docker push strangeloop1710/fpl-api:latest
  deploy:
    needs: tag-backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible
      uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
        GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
        INVENTORY: ./deployment/inventory.yml
        PLAYBOOK: ./deployment/deploy-playbook.yml
